# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "fm_yaml_db"
  s.version = "0.2.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Adam Wiggins", "Orion Henry"]
  s.date = "2012-09-19"
  s.description = "Forked gem from yaml_db - the great DB independent dumper for rails devs"
  s.email = "skullzeek@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.markdown",
    "README.rdoc"
  ]
  s.files = [
    ".Gemfile.swp",
    ".document",
    ".travis.yml",
    "Gemfile",
    "LICENSE.txt",
    "README.markdown",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "about.yml",
    "fm_yaml_db.gemspec",
    "init.rb",
    "lib/csv_db.rb",
    "lib/serialization_helper.rb",
    "lib/tasks/yaml_db_tasks.rake",
    "lib/yaml_db.rb",
    "spec/base.rb",
    "spec/serialization_helper_base_spec.rb",
    "spec/serialization_helper_dump_spec.rb",
    "spec/serialization_helper_load_spec.rb",
    "spec/serialization_utils_spec.rb",
    "spec/yaml_dump_spec.rb",
    "spec/yaml_load_spec.rb",
    "spec/yaml_utils_spec.rb"
  ]
  s.homepage = "http://github.com/kalabiyau/yaml_db"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "fork of a great yaml_db gem"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<rails>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end

